### ISSUE TITLE
Exceptions not handled

### ISSUE THREAD

**Issue by rmw1075** [rmw1075/iste330_project#15]
exceptions are not handled properly.

Example: if you do Paper paper_entity = paperFacade._getPaper_(idOfNonexistantPaper), you get an _IndexOutOfBoundException_ thrown.

Probably should either:
A) Handle the possibility of an empty result in each of the facade's get methods.
B) Create our own exceptions

**Comment by NicholasFeldman** [comment]
This seems like a DAO layer issue, probably like here https://github.com/rmw1075/iste330_project/blob/e0adbead6496369aa19fdaf207d9d87cd5726257/src/main/java/io/github/rmw1075/iste330project/dao/PaperDao.java#L108 it should return null if the resultset is empty

**Comment by rmw1075** [comment]
Yes, you're right. I found the issue: I was catching a _NullPointerException_ instead of an _IndexOutOfBoundsException_.

But that brings up another issue: if I were to do paper_entity.getTitle() on the null paper_entity, I get a _NullPointerException_ that still isnt handled.

**Comment by rmw1075** [comment]
fixed
